//
//  SuperHero.swift
//  SuperKahramanSwiftUI
//
//  Created by Ahmet Karaman on 17.08.2024.
//

import Foundation
import SwiftUI
import CoreLocation

struct SuperHero : Identifiable {
    var id = UUID()
    var name : String
    var realName :String
    var imageName : String
    var city : String
    var job : String
    var cordinate : Coordinate
    var about : String
    
    //direkt konum belirtmek istediğimizde  cll ile kordinat oluşturalım enlem boylamla uğraşmaualım
    var cordinateLocation : CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude:cordinate.latitude, longitude: cordinate.longitude)
    }
    
}

struct Coordinate {
    
    var latitude : Double
    var longitude : Double
}

let batman = SuperHero(name: "Batman", realName: "Bruce Wayne", imageName: "batman", city: "Gotham", job: "Business Man", cordinate: Coordinate(latitude: 41.850692, longitude: -87.614697), about: "Batman[a] is a superhero who appears in American comic books published by DC Comics. Batman was created by the artist Bob Kane and writer Bill Finger, and debuted in the 27th issue of the comic book Detective Comics on March 30, 1939. In the DC Universe, Batman is the alias of Bruce Wayne, a wealthy American playboy, philanthropist, and industrialist who resides in Gotham City. His origin story features him swearing vengeance against criminals after witnessing the murder of his parents, Thomas and Martha, as a child, a vendetta tempered by the ideal of justice. He trains himself physically and intellectually, crafts a bat-inspired persona, and monitors the Gotham streets at night. Kane, Finger, and other creators accompanied Batman with supporting characters, including his sidekicks Robin and Batgirl; allies Alfred Pennyworth and James Gordon; love interest Catwoman; and foes such as the Penguin, the Riddler, Two-Face, and his archenemy, the Joker. Kane conceived Batman in early 1939 to capitalize on the popularity of Superman; although Kane frequently claimed sole creation credit, Finger substantially developed the concept from a generic superhero into something more bat-like. They drew inspiration from pulp fiction characters like the Shadow and Sherlock Holmes. Batman received a spin-off publication, Batman, in 1940. Kane and Finger introduced Batman as a ruthless vigilante who frequently killed or maimed criminals, but he evolved into a just, disciplined superhero with a stringent moral code that prohibits killing during the 1940s. Unlike most superheroes, Batman does not possess any superpowers, instead relying on his intellect, fighting skills, and wealth. The 1960s Batman television series used a camp aesthetic, which continued to be associated with Batman for years after it ended. Various creators worked to return Batman to his darker roots in the 1970s and 1980s, culminating with the 1986 miniseries The Dark Knight Returns by Frank Miller.")

let superman = SuperHero(name: "Superman", realName: "Clark Kent", imageName: "superman", city: "Kansas", job: "Journalist", cordinate: Coordinate(latitude: 39.0865207, longitude: -94.7089592), about: "Superman is a superhero who appears in American comic books published by DC Comics. The character was created by writer Jerry Siegel and artist Joe Shuster, and debuted in the comic book Action Comics #1 (cover-dated June 1938 and published April 18, 1938).[1] Superman has been adapted to a number of other media, which includes radio serials, novels, films, television shows, theater, and video games.Superman was born on the fictional planet Krypton with the birth name of Kal-El. As a baby, his parents Jor-El and Lara sent him to Earth in a small spaceship shortly before Krypton was destroyed in a natural cataclysm. His ship landed in the American countryside near the fictional town of Smallville, Kansas. He was found and adopted by farmers Jonathan and Martha Kent, who named him Clark Kent. Clark began developing superhuman abilities, such as incredible strength and impervious skin. His adoptive parents advised him to use his powers to benefit of humanity, and he decided to fight crime as a vigilante. To protect his personal life, he changes into a colorful costume and uses the alias Superman when fighting crime. Clark resides in the fictional American city of Metropolis, where he works as a journalist for the Daily Planet. Superman's supporting characters include his love interest and fellow journalist Lois Lane, Daily Planet photographer Jimmy Olsen, and editor-in-chief Perry White, and his enemies include Brainiac, General Zod, and archenemy Lex Luthor.")

let spiderman = SuperHero(name: "Spiderman", realName: "Peter Parker", imageName: "spiderman", city: "New York", job: "Photographer", cordinate: Coordinate(latitude: 40.7160119, longitude: -74.0524729), about: "Spider-Man is a superhero in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and artist Steve Ditko, he first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books. He has been featured in comic books, television shows, films, video games, novels, and plays. Spider-Man's secret identity is Peter Benjamin Parker. Initially, Peter was depicted as a teenage high-school student and an orphan raised by his Aunt May and Uncle Ben in New York City after his parents, Richard and Mary Parker, died in a plane crash. Lee, Ditko, and later creators had the character deal with the struggles of adolescence and young adulthood and gave him many supporting characters, such as Flash Thompson, J. Jonah Jameson, and Harry Osborn; romantic interests Gwen Stacy, Mary Jane Watson, and the Black Cat; and enemies such as Doctor Octopus, the Green Goblin, and Venom. In his origin story, Spider-Man gets his superhuman spider powers and abilities after being bitten by a radioactive spider. These powers include superhuman strength, agility, reflexes, stamina, durability, coordination, and balance; clinging to surfaces and ceilings like a spider; and detecting danger with his precognition ability called 'spider-sense'. He builds wrist-mounted 'web-shooter' devices that shoot artificial spider-webs of his own design, which he uses both for fighting and web-swinging across the city. Peter Parker initially used his powers for his personal gain, but after his Uncle Ben was killed by a thief that Peter could not stop, he began to use his powers to fight crime by becoming Spider-Man.")

let ironman = SuperHero(name: "Iron Man", realName: "Tony Stark", imageName: "ironman", city: "Los Angelese", job: "Business Man", cordinate: Coordinate(latitude: 33.8003309, longitude: -118.2261494), about: "Iron Man is a superhero appearing in American comic books published by Marvel Comics. Co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby, the character first appeared in Tales of Suspense #39 in 1962 (cover dated March 1963) and received his own title with Iron Man #1 in 1968. Shortly after his creation, Iron Man became a founding member of the superhero team, the Avengers, with Thor, Ant-Man, the Wasp, and the Hulk. Iron Man stories, individually and with the Avengers, have been published consistently since the character's creation.Iron Man is the superhero persona of Anthony Edward 'Tony' Stark, a businessman and engineer who runs the weapons manufacturing company Stark Industries. When Stark was captured in a war zone and sustained a severe heart wound, he built his Iron Man armor and escaped his captors. Iron Man's suits of armor grant him superhuman strength, flight, energy projection, and other abilities. The character was created in response to the Vietnam War as Lee's attempt to create a likeable pro-war character. Since his creation, Iron Man has been used to explore political themes, with early Iron Man stories being set in the Cold War. The character's role as a weapons manufacturer proved controversial, and Marvel moved away from geopolitics by the 1970s. Instead, the stories began exploring themes such as civil unrest, technological advancement, corporate espionage, alcoholism, and governmental authority.")


let hulk = SuperHero(name: "Hulk", realName: "Bruce Banner", imageName: "hulk", city: "Washigton", job: "Worker", cordinate: Coordinate(latitude: 38.928598, longitude: -77.083586), about: "The Hulk is a superhero appearing in American comic books published by Marvel Comics. Created by writer Stan Lee and artist Jack Kirby, the character first appeared in the debut issue of The Incredible Hulk (May 1962). In his comic book appearances, the character, who has dissociative identity disorder (DID), is primarily represented by the alter ego Hulk, a green-skinned, hulking, and muscular humanoid possessing a limitless degree of physical strength, and the alter ego Dr. Robert Bruce Banner, a physically weak, socially withdrawn, and emotionally reserved physicist, both of whom typically resent each other.Following his accidental exposure to gamma rays while saving the life of Rick Jones during the detonation of an experimental bomb, Banner is physically transformed into the Hulk when subjected to emotional stress, at or against his will. This transformation often leads to destructive rampages and conflicts that complicate Banner's civilian life. The Hulk's level of strength is usually conveyed proportionate to his anger level. Commonly portrayed as a raging savage, the Hulk has been represented with other alter egos, from a mindless, destructive force (War) to a brilliant warrior (World-Breaker), a self-hating protector (the Devil/Immortal), a genius scientist in his own right (Doc Green), and a gangster (Joe Fixit). Despite Hulk and Banner's desire for solitude, the character has a large supporting cast. This includes Banner's love interest Betty Ross, his best friend, Rick Jones, his cousin She-Hulk, and therapist and ally Doc Samson. In addition, the Hulk alter ego has many key supporting characters, like his co-founders of the superhero team the Avengers, his queen Caiera, fellow warriors Korg and Miek, and sons Skaar and Hiro-Kala. However, his uncontrollable power has brought him into conflict with his fellow heroes and others. Despite this, he tries his best to do what's right while battling villains such as the Leader, the Abomination, the Absorbing Man, and more. Lee stated that the Hulk's creation was inspired by a combination of Frankenstein and Dr. Jekyll and Mr. Hyde.[4] Although the Hulk's coloration has varied throughout the character's publication history, the usual color is green.")


let arrayOfHeros = [batman, superman, spiderman, ironman, hulk]


